---
version: "2"
linters:
  default: all
  disable:
    - copyloopvar
    - depguard
    - exhaustruct
    - intrange
    - wsl
  settings:
    varnamelen:
      ignore-type-assert-ok: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
