on: push
name: Build and test
jobs:
  go_generate:
    name: Check generated code is up to date
    if: '!github.event.deleted'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        path: go/src/arnested.dk/go/triagebot
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.13'
    - name: go generate
      env:
        GO111MODULE: 'on'
        GOPATH: ${{ github.workspace }}/go
      run: (cd go/src/arnested.dk/go/triagebot && go generate -x)
    - name: Diff after go generate
      run: (cd go/src/arnested.dk/go/triagebot && git diff --exit-code)
  build_and_test:
    name: Build and test
    if: '!github.event.deleted'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.13', '1.14']
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: go test
      env:
        GO111MODULE: 'on'
      run: go test -v -race -cover -covermode=atomic -coverprofile=coverage.txt ./...
    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@v1.5.0
      env:
        CODECOV_ENV: ${{ matrix.go-version }}
      with:
        token: ${{secrets.CODECOV_TOKEN}}
  license_check:
    name: License check
    if: '!github.event.deleted'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.13'
    - name: Install wwhrd
      env:
        GO111MODULE: 'off'
      run: go get -u github.com/frapposelli/wwhrd
    - name: go mod vendor
      env:
        GO111MODULE: 'on'
      run: go mod vendor
    - name: wwhrd check
      run: $(go env GOPATH)/bin/wwhrd check
  deploy:
    name: Deploy
    if: github.ref == 'refs/heads/master' && !github.event.deleted
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GCLOUD_AUTH }}
    - run: gcloud functions deploy ${{secrets.GCF_NAME}} --project=${{secrets.GCF_PROJECT}} --region=${{secrets.GCF_REGION}}
          --entry-point=Handle --runtime=go113 --trigger-http --memory=128M
          --format='yaml(status,updateTime,versionId)'
