on: push
name: Build and test
jobs:
  go_generate:
    name: Check generated code is up to date
    if: '!github.event.deleted'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: go/src/arnested.dk/go/triagebot
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.13'
    - name: go generate
      env:
        GO111MODULE: 'on'
        GOPATH: ${{ github.workspace }}/go
      run: (cd go/src/arnested.dk/go/triagebot && go generate -x)
    - name: Diff after go generate
      run: (cd go/src/arnested.dk/go/triagebot && git diff --exit-code)
  build_and_test:
    name: Build and test
    if: '!github.event.deleted'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.11', '1.12', '1.13', '1.14']
    steps:
    - uses: actions/checkout@v2
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: go test
      env:
        GO111MODULE: 'on'
      run: go test -v -race -cover -covermode=atomic -coverprofile=coverage.txt ./...
    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@v1
      env:
        CODECOV_ENV: ${{ matrix.go-version }}
      with:
        token: ${{secrets.CODECOV_TOKEN}}
  license_check:
    name: License check
    if: '!github.event.deleted'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.13'
    - name: Install wwhrd
      env:
        GO111MODULE: 'off'
      run: go get -u github.com/frapposelli/wwhrd
    - name: go mod vendor
      env:
        GO111MODULE: 'on'
      run: go mod vendor
    - name: wwhrd check
      run: $(go env GOPATH)/bin/wwhrd check
