on: push
name: Build and test
jobs:
  go-versions:
    name: Lookup go versions
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.versions.outputs.matrix }}
      minimal: ${{ steps.versions.outputs.minimal }}
    steps:
    - uses: actions/checkout@v2
    - uses: arnested/go-version-action@v1
      id: versions
      env:
        GITHUB_TOKEN: ${{ github.token }}
  go_generate:
    name: Check generated code is up to date
    needs: go-versions
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: go/src/arnested.dk/go/triagebot
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ needs.go-versions.outputs.minimal }}
    - name: go generate
      env:
        GO111MODULE: 'on'
        GOPATH: ${{ github.workspace }}/go
      run: (cd go/src/arnested.dk/go/triagebot && go generate -x)
    - name: Diff after go generate
      run: (cd go/src/arnested.dk/go/triagebot && git diff --exit-code)
  build_and_test:
    name: Build and test
    needs: go-versions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ${{ fromJSON(needs.go-versions.outputs.matrix) }}
    steps:
    - uses: actions/checkout@v2
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: go test
      env:
        GO111MODULE: 'on'
      run: go test -v -race -cover -covermode=atomic -coverprofile=coverage.txt ./...
    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@v2
      env:
        CODECOV_ENV: ${{ matrix.go-version }}
  license_check:
    name: License check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ needs.go-versions.outputs.minimal }}
    - name: Install wwhrd
      env:
        GO111MODULE: 'off'
      run: go get -u github.com/frapposelli/wwhrd
    - name: go mod vendor
      env:
        GO111MODULE: 'on'
      run: go mod vendor
    - name: wwhrd check
      run: $(go env GOPATH)/bin/wwhrd check
  deploy:
    name: Deploy
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
    - uses: actions/checkout@v2
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GCLOUD_AUTH }}
    - run: echo ::set-output name=go-runtime::$(echo -n go${{ needs.go-versions.outputs.minimal }} | tr -d '.')
      id: runtime
    - run: gcloud functions deploy ${{secrets.GCF_NAME}} --project=${{secrets.GCF_PROJECT}} --region=${{secrets.GCF_REGION}}
          --entry-point=Handle --runtime=${{ steps.runtime.outputs.go-runtime }} --trigger-http --memory=128M
          --format='yaml(status,updateTime,versionId)'
    - name: Post status to Zulip
      if: ${{ always() }}
      uses: containrrr/shoutrrr-action@v1
      with:
        url: "${{ secrets.ZULIP_SHOUTRRR_URL }}?stream=logs&topic=triagebot"
        message: "Deployed `${{ github.repository }}`@`${{ github.sha }}` to Google Cloud Function `${{ secrets.CF_NAME }}`@`${{ secrets.CF_PROJECT }}`: **${{ job.status }}**."
