name: Release
on:
  workflow_run:
    workflows: ["Build and test"]
    branches: [main]
    types:
      - completed

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: arnested/go-version-action@v1
      id: version
    - run: echo ::set-output name=go-runtime::$(echo -n go${{ steps.version.outputs.go-mod-version }} | tr -d '.')
      id: runtime
    - uses: google-github-actions/auth@v2
      with:
        credentials_json: "${{ secrets.GCLOUD_AUTH }}"
    - uses: google-github-actions/deploy-cloud-functions@v2
      with:
        name: ${{ secrets.GCF_NAME }}
        region: ${{ secrets.GCF_REGION }}
        project_id: ${{ secrets.GCF_PROJECT }}
        runtime: ${{ steps.runtime.outputs.go-runtime }}
        entry_point: "Handle"
        memory_mb: 128
        env_vars: TRIAGEBOT_JIRA_USER=${{ secrets.TRIAGEBOT_JIRA_USER }},TRIAGEBOT_JIRA_PASS=${{ secrets.TRIAGEBOT_JIRA_PASS }},TRIAGEBOT_JIRA_FILTER=22400,ZULIP_TOKEN=${{ secrets.ZULIP_TOKEN }},ZULIP_BOT_MAIL=${{ secrets.ZULIP_BOT_MAIL }},ZULIP_BOT_APIKEY=${{ secrets.ZULIP_BOT_APIKEY }},TZ=Europe/Copenhagen,TRIAGEBOT_JIRA_FILTER_UNRELEASED=28200
    - name: Post status to Zulip
      if: ${{ always() }}
      uses: containrrr/shoutrrr-action@v1
      with:
        url: "${{ secrets.ZULIP_SHOUTRRR_URL }}?stream=logs&topic=triagebot"
        message: "Deployed `${{ github.repository }}`@`${{ github.sha }}` to Google Cloud Function `${{ secrets.GCF_NAME }}`@`${{ secrets.GCF_PROJECT }}`: **${{ job.status }}**."
